### ISSUE TITLE
Guidance on starting VMs with all FluidMem memory

### ISSUE THREAD

**Issue by annapanag** [blakecaldwell/fluidmem#1]
Greetings,

I would like to boot a qemu VM with all FluidMem memory, using the libvirt tool for convenience.
Is it possible if you could give me a guidance on how to accomplish this?

**Comment by blakecaldwell** [comment]
Sure, it is possible with a small change to the libvirt patch, but it will apply to all VMs started with the newly compiled `libvirtd`. Change the following lines
https://github.com/blakecaldwell/fluidmem/blob/master/patches/libvirt/0001-libvirt-elastic-memory-backend.patch#L67-L70

To just
```
*backendType = memory-backend-elastic
```

While libvirt was convenient for initially creating VMs, I found that directly starting the VM with qemu was useful for creating specific NUMA topologies. I used the qemu command from an OpenStack deployment as a template. Here's the memory part of a qemu command (missing disk and network config) that I used.
```
/usr/bin/qemu-system-x86_64 -name instance-000002bd -machine pc-i440fx-2.4,accel=kvm,usb=off -cpu Broadwell,+abm,+pdpe1gb,+rdrand,+f16c,+osxsave,+dca,+pdcm,+xtpr,+tm2,+est,+smx,+vmx,+ds_cpl,+dtes64,+pbe,+tm,+ht,+ss,+acpi,+ds,+vme -m size=4194304k,slots=4,maxmem=1125899906842624k -realtime mlock=off -smp 3,sockets=3,cores=1,threads=1 -object memory-backend-elastic,id=ram-node0,size=4290772992,host-nodes=0,policy=bind -numa node,nodeid=0,cpus=0-1,memdev=ram-node0 -object memory-backend-elastic,id=ram-node1,size=4194304,host-nodes=1,policy=bind -numa node,nodeid=1,cpus=2,memdev=ram-node1
```
